# ---------------------------------------------------------------------------- #
#                                                                              #
#              E v a l u a t i o n B o a r d . p r o p e r t i e s             #
#                                                                              #
# ---------------------------------------------------------------------------- #

# This file gathers resources to be injected in the EntityBoard class
#
# This is the generic version

grade.text                  = Grade of the evaluation
grade.active.toolTipText    = Assignable shape
grade.toolTipText           = Evaluated shape
