# ---------------------------------------------------------------------------- #
#                                                                              #
#             S y m b o l G l y p h B o a r d . p r o p e r t i e s            #
#                                                                              #
# ---------------------------------------------------------------------------- #

# This file gathers resources to be injected in the SymbolGlyphBoard class
#
# This is the generic version

weight.text                 = Weight
weight.toolTipText          = Normalized weight
weight.field.toolTipText    = ${weight.toolTipText}

width.text                  = Width
width.toolTipText           = Normalized width
width.field.toolTipText     = ${width.toolTipText}

height.text                 = Height
height.toolTipText          = Normalized height
height.field.toolTipText    = ${height.toolTipText}
