# ---------------------------------------------------------------------------- #
#                                                                              #
#                 S e c t i o n B o a r d . p r o p e r t i e s                #
#                                                                              #
# ---------------------------------------------------------------------------- #

# This file gathers resources to be injected in the SectionBoard class
#
# This is the generic version

x.text                      = X
x.toolTipText               = Left abscissa in pixels
x.field.toolTipText         = ${x.toolTipText}

y.text                      = Y
y.toolTipText               = Top ordinate in pixels
y.field.toolTipText         = ${y.toolTipText}

weight.text                 = Weight
weight.toolTipText          = Number of pixels in this section
weight.field.toolTipText    = ${weight.toolTipText}

width.text                  = Width
width.toolTipText           = Width in pixels
width.field.toolTipText     = ${width.toolTipText}

height.text                 = Height
height.toolTipText          = Height in pixels
height.field.toolTipText    = ${height.toolTipText}
