package org.audiveris.omr.dws;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.Arrays;

/**
 * Class {@code SymbolFactory} produces the symbol corresponding to the symbol ID.
 *
 * @author Raphael Emberger
 */
public class SymbolFactory {

    //~ Static fields/initializers -----------------------------------------------------------------

    private static final Logger logger = LoggerFactory.getLogger(SymbolFactory.class);

    private static final ArrayList<Symbol> symbols = new ArrayList<>(Arrays.asList(
            new Symbol(0, "none", "No valid symbol"),
            new Symbol(1, "brace", "Brace"),
            new Symbol(2, "bracketTop", "Bracket top"),
            new Symbol(3, "bracketBottom", "Bracket bottom"),
            new Symbol(4, "legerLine", "Leger line"),
            new Symbol(5, "barlineSingle", "Single barline"),
            new Symbol(6, "barlineDouble", "Double barline"),
            new Symbol(7, "barlineFinal", "Final barline"),
            new Symbol(8, "barlineReverseFinal", "Reverse final barline"),
            new Symbol(9, "barlineHeavy", "Heavy barline"),
            new Symbol(10, "barlineHeavyHeavy", "Heavy double barline"),
            new Symbol(11, "barlineDashed", "Dashed barline"),
            new Symbol(12, "barlineDotted", "Dotted barline"),
            new Symbol(13, "repeatLeft", "Left (start) repeat sign"),
            new Symbol(14, "repeatRight", "Right (end) repeat sign"),
            new Symbol(15, "repeatRightLeft", "Right and left repeat sign"),
            new Symbol(16, "repeatDots", "Repeat dots"),
            new Symbol(17, "repeatDot", "Repeat dot"),
            new Symbol(18, "dalSegno", "Dal segno (D.S.)"),
            new Symbol(19, "daCapo", "Da capo (D.C.)"),
            new Symbol(20, "segno", "Segno"),
            new Symbol(21, "coda", "Coda"),
            new Symbol(22, "codaSquare", "Square coda"),
            new Symbol(23, "gClef", "G clef"),
            new Symbol(24, "gClef8vb", "G clef ottava bassa"),
            new Symbol(25, "gClef8va", "G clef ottava alta"),
            new Symbol(26, "gClef15mb", "G clef quindicesima bassa"),
            new Symbol(27, "gClef15ma", "G clef quindicesima alta"),
            new Symbol(28, "cClefAlto", "C clef alto"),
            new Symbol(29, "cClefTenor", "C clef tenor"),
            new Symbol(30, "fClef", "F clef"),
            new Symbol(31, "fClef8vb", "F clef ottava bassa"),
            new Symbol(32, "fClef8va", "F clef ottava alta"),
            new Symbol(33, "fClef15mb", "F clef quindicesima bassa"),
            new Symbol(34, "fClef15ma", "F clef quindicesima alta"),
            new Symbol(35, "unpitchedPercussionClef1", "Unpitched percussion clef 1"),
            new Symbol(36, "gClefChange", "G clef change"),
            new Symbol(37, "cClefAltoChange", "C clef alto change"),
            new Symbol(38, "cClefTenorChange", "C clef tenor change"),
            new Symbol(39, "fClefChange", "F clef change"),
            new Symbol(40, "clef8", "8 for clefs"),
            new Symbol(41, "clef15", "15 for clefs"),
            new Symbol(42, "timeSig0", "Time signature 0"),
            new Symbol(43, "timeSig1", "Time signature 1"),
            new Symbol(44, "timeSig2", "Time signature 2"),
            new Symbol(45, "timeSig3", "Time signature 3"),
            new Symbol(46, "timeSig4", "Time signature 4"),
            new Symbol(47, "timeSig5", "Time signature 5"),
            new Symbol(48, "timeSig6", "Time signature 6"),
            new Symbol(49, "timeSig7", "Time signature 7"),
            new Symbol(50, "timeSig8", "Time signature 8"),
            new Symbol(51, "timeSig9", "Time signature 9"),
            new Symbol(52, "timeSig12", "Time signature 12"),
            new Symbol(53, "timeSig16", "Time signature 16"),
            new Symbol(54, "timeSigCommon", "Common time"),
            new Symbol(55, "timeSigCutCommon", "Cut time"),
            new Symbol(56, "timeSig2over4", "2/4 time signature"),
            new Symbol(57, "timeSig2over2", "2/2 time signature"),
            new Symbol(58, "timeSig3over2", "3/2 time signature"),
            new Symbol(59, "timeSig3over4", "3/4 time signature"),
            new Symbol(60, "timeSig3over8", "3/8 time signature"),
            new Symbol(61, "timeSig4over4", "4/4 time signature"),
            new Symbol(62, "timeSig5over4", "5/4 time signature"),
            new Symbol(63, "timeSig5over8", "5/8 time signature"),
            new Symbol(64, "timeSig6over4", "6/4 time signature"),
            new Symbol(65, "timeSig6over8", "6/8 time signature"),
            new Symbol(66, "timeSig7over8", "7/8 time signature"),
            new Symbol(67, "timeSig9over8", "9/8 time signature"),
            new Symbol(68, "timeSig12over8", "12/8 time signature"),
            new Symbol(69, "noteheadBlack", "Black notehead"),
            new Symbol(70, "noteheadBlackSmall", "Black notehead (small staff)"),
            new Symbol(71, "noteheadHalf", "Half (minim) notehead"),
            new Symbol(72, "noteheadHalfSmall", "Half (minim) notehead (small staff)"),
            new Symbol(73, "noteheadWhole", "Whole (semibreve) notehead"),
            new Symbol(74, "noteheadWholeSmall", "Whole notehead (small staff)"),
            new Symbol(75, "noteheadDoubleWhole", "Double whole (breve) notehead"),
            new Symbol(76, "noteheadDoubleWholeSmall", "Double whole note (breve) (small staff)"),
            new Symbol(77, "noteheadXBlack", "X notehead black"),
            new Symbol(78, "noteheadXHalf", "X notehead half"),
            new Symbol(79, "noteheadXWhole", "X notehead whole"),
            new Symbol(80, "augmentationDot", "Augmentation dot"),
            new Symbol(81, "stem", "Combining stem"),
            new Symbol(82, "tremolo1", "Combining tremolo 1"),
            new Symbol(83, "tremolo2", "Combining tremolo 2"),
            new Symbol(84, "tremolo3", "Combining tremolo 3"),
            new Symbol(85, "tremolo4", "Combining tremolo 4"),
            new Symbol(86, "tremolo5", "Combining tremolo 5"),
            new Symbol(87, "flag8thUp", "Combining flag 1 (8th) above"),
            new Symbol(88, "flag8thUpSmall", "Combining flag 1 (8th) above (small staff)"),
            new Symbol(89, "flag16thUp", "Combining flag 2 (16th) above"),
            new Symbol(90, "flag32ndUp", "Combining flag 3 (32nd) above"),
            new Symbol(91, "flag64thUp", "Combining flag 4 (64th) above"),
            new Symbol(92, "flag128thUp", "Combining flag 5 (128th) above"),
            new Symbol(93, "flag256thUp", "Combining flag 6 (256th) above"),
            new Symbol(94, "flag512thUp", "Combining flag 7 (512th) above"),
            new Symbol(95, "flag1024thUp", "Combining flag 8 (1024th) above"),
            new Symbol(96, "flag8thDown", "Combining flag 1 (8th) below"),
            new Symbol(97, "flag8thDownSmall", "Combining flag 1 (8th) below (small staff)"),
            new Symbol(98, "flag16thDown", "Combining flag 2 (16th) below"),
            new Symbol(99, "flag32ndDown", "Combining flag 3 (32nd) below"),
            new Symbol(100, "flag64thDown", "Combining flag 4 (64th) below"),
            new Symbol(101, "flag128thDown", "Combining flag 5 (128th) below"),
            new Symbol(102, "flag256thDown", "Combining flag 6 (256th) below"),
            new Symbol(103, "flag512thDown", "Combining flag 7 (512th) below"),
            new Symbol(104, "flag1024thDown", "Combining flag 8 (1024th) below"),
            new Symbol(105, "accidentalFlat", "Flat"),
            new Symbol(106, "accidentalFlatSmall", "Flat (for small staves)"),
            new Symbol(107, "accidentalNatural", "Natural"),
            new Symbol(108, "accidentalNaturalSmall", "Natural (for small staves)"),
            new Symbol(109, "accidentalSharp", "Sharp"),
            new Symbol(110, "accidentalSharpSmall", "Sharp (for small staves)"),
            new Symbol(111, "accidentalDoubleSharp", "Double sharp"),
            new Symbol(112, "accidentalDoubleFlat", "Double flat"),
            new Symbol(113, "keyFlat", "Flat in key signature"),
            new Symbol(114, "keyNatural", "Natural in key signature"),
            new Symbol(115, "keySharp", "Sharp in key signature"),
            new Symbol(116, "articAccentAbove", "Accent above"),
            new Symbol(117, "articAccentBelow", "Accent below"),
            new Symbol(118, "articStaccatoAbove", "Staccato above"),
            new Symbol(119, "articStaccatoBelow", "Staccato below"),
            new Symbol(120, "articTenutoAbove", "Tenuto above"),
            new Symbol(121, "articTenutoBelow", "Tenuto below"),
            new Symbol(122, "articStaccatissimoAbove", "Staccatissimo above"),
            new Symbol(123, "articStaccatissimoBelow", "Staccatissimo below"),
            new Symbol(124, "articMarcatoAbove", "Marcato above"),
            new Symbol(125, "articMarcatoBelow", "Marcato below"),
            new Symbol(126, "articTenutoStaccatoAbove", "Louré (tenuto-staccato) above"),
            new Symbol(127, "articTenutoStaccatoBelow", "Louré (tenuto-staccato) below"),
            new Symbol(128, "fermataAbove", "Fermata above staff"),
            new Symbol(129, "fermataBelow", "Fermata below staff"),
            new Symbol(130, "breathMarkComma", "Breath mark (comma)"),
            new Symbol(131, "caesura", "Caesura"),
            new Symbol(132, "restMaxima", "Maxima rest"),
            new Symbol(133, "restLonga", "Longa rest"),
            new Symbol(134, "restDoubleWhole", "Double whole (breve) rest"),
            new Symbol(135, "restWhole", "Whole (semibreve) rest"),
            new Symbol(136, "restHalf", "Half (minim) rest"),
            new Symbol(137, "restQuarter", "Quarter (crotchet) rest"),
            new Symbol(138, "rest8th", "Eighth (quaver) rest"),
            new Symbol(139, "rest16th", "16th (semiquaver) rest"),
            new Symbol(140, "rest32nd", "32nd (demisemiquaver) rest"),
            new Symbol(141, "rest64th", "64th (hemidemisemiquaver) rest"),
            new Symbol(142, "rest128th", "128th (semihemidemisemiquaver) rest"),
            new Symbol(143, "rest256th", "256th rest"),
            new Symbol(144, "rest512th", "512th rest"),
            new Symbol(145, "rest1024th", "1024th rest"),
            new Symbol(146, "restHBar", "Multiple measure rest"),
            new Symbol(147, "ottavaAlta", "Ottava alta (8va)"),
            new Symbol(148, "ottavaBassaVb", "Ottava bassa (8vb)"),
            new Symbol(149, "dynamicPiano", "Piano (p)"),
            new Symbol(150, "dynamicMezzo", "Mezzo (m)"),
            new Symbol(151, "dynamicForte", "Forte (f)"),
            new Symbol(152, "dynamicRinforzando", "Rinforzando (r)"),
            new Symbol(153, "dynamicSforzando", "Sforzando (s)"),
            new Symbol(154, "dynamicZ", "Z"),
            new Symbol(155, "dynamicNiente", "Niente (n)"),
            new Symbol(156, "dynamicPPPPPP", "pppppp"),
            new Symbol(157, "dynamicPPPPP", "ppppp"),
            new Symbol(158, "dynamicPPPP", "pppp"),
            new Symbol(159, "dynamicPPP", "ppp"),
            new Symbol(160, "dynamicPP", "pp"),
            new Symbol(161, "dynamicMP", "mp"),
            new Symbol(162, "dynamicMF", "mf"),
            new Symbol(163, "dynamicPF", "pf"),
            new Symbol(164, "dynamicFF", "ff"),
            new Symbol(165, "dynamicFFF", "fff"),
            new Symbol(166, "dynamicFFFF", "ffff"),
            new Symbol(167, "dynamicFFFFF", "fffff"),
            new Symbol(168, "dynamicFFFFFF", "ffffff"),
            new Symbol(169, "dynamicFortePiano", "Forte-piano (fp)"),
            new Symbol(170, "dynamicForzando", "Forzando (fz)"),
            new Symbol(171, "dynamicSforzando1", "Sforzando 1 (sf)"),
            new Symbol(172, "dynamicSforzandoPiano", "Sforzando-piano (sfp)"),
            new Symbol(173, "dynamicSforzandoPianissimo", "Sforzando-pianissimo (sfpp)"),
            new Symbol(174, "dynamicSforzato", "Sforzato (sfz)"),
            new Symbol(175, "dynamicSforzatoPiano", "Sforzato-piano (sfzp)"),
            new Symbol(176, "dynamicSforzatoFF", "Sforzatissimo (sffz)"),
            new Symbol(177, "dynamicRinforzando1", "Rinforzando 1 (rf)"),
            new Symbol(178, "dynamicRinforzando2", "Rinforzando 2 (rfz)"),
            new Symbol(179, "graceNoteAcciaccaturaStemUp", "Slashed grace note stem up"),
            new Symbol(180, "graceNoteAppoggiaturaStemUp", "Grace note stem up"),
            new Symbol(181, "graceNoteAcciaccaturaStemDown", "Slashed grace note stem down"),
            new Symbol(182, "graceNoteAppoggiaturaStemDown", "Grace note stem down"),
            new Symbol(181, "ornamentTrill", "Trill"),
            new Symbol(182, "ornamentTurn", "Turn"),
            new Symbol(183, "ornamentTurnInverted", "Inverted turn"),
            new Symbol(184, "ornamentTurnSlash", "Turn with slash"),
            new Symbol(185, "ornamentTurnUp", "Turn up"),
            new Symbol(186, "ornamentMordent", "Mordent"),
            new Symbol(187, "ornamentMordentInverted", "Inverted mordent"),
            new Symbol(188, "stringsDownBow", "Down bow"),
            new Symbol(189, "stringsUpBow", "Up bow"),
            new Symbol(190, "arpeggiato", "Arpeggiato"),
            new Symbol(191, "keyboardPedalPed", "Pedal mark"),
            new Symbol(192, "keyboardPedalUp", "Pedal up mark"),
            new Symbol(193, "tuplet3", "Tuplet 3"),
            new Symbol(194, "tuplet6", "Tuplet 6"),
            new Symbol(195, "fingering0", "Fingering 0 (open string)"),
            new Symbol(196, "fingering1", "Fingering 1 (thumb)"),
            new Symbol(197, "fingering2", "Fingering 2 (index finger)"),
            new Symbol(198, "fingering3", "Fingering 3 (middle finger)"),
            new Symbol(199, "fingering4", "Fingering 4 (ring finger)"),
            new Symbol(200, "fingering5", "Fingering 5 (little finger)"),
            new Symbol(201, "fingeringPLower", "Fingering p (pulgar; right-hand thumb"),
            new Symbol(202, "fingeringILower", "Fingering i (indicio; right-hand index finger for guitar)"),
            new Symbol(203, "fingeringMLower", "Fingering m (medio; right-hand middle finger for guitar)"),
            new Symbol(204, "fingeringALower", "Fingering a (anular; right-hand ring finger for guitar)")));

    //~ Methods ------------------------------------------------------------------------------------
    //---------//
    // produce //
    //---------//

    /**
     * Produces the symbol preset to the corresponding symbol ID.
     *
     * @param symbolId Identifier for the symbol.
     * @return The symbol if found, otherwise null;
     */
    public static Symbol produce(final String symbolId) {
        Symbol sym = null;
        for (Symbol symbol : symbols) {
            if (symbol.getSymbolId().equals(symbolId)) {
                sym = symbol.deepCopy();
            }
        }
        if (sym == null) {
            logger.warn("No symbol found for ID \"" + symbolId + "\"");
        }
        return sym;
    }
}
