# ---------------------------------------------------------------------------- #
#                                                                              #
#                  B i n a r y B o a r d . p r o p e r t i e s                 #
#                                                                              #
# ---------------------------------------------------------------------------- #

# This file gathers resources to be injected in the BinaryBoard class
#
# This is the generic version

# Color names

black = black
white = white

# Components

color.text                  = Binary color
color.toolTipText           = Resulting binary color
color.field.toolTipText     = ${color.toolTipText}

mean.text                   = Observed mean
mean.toolTipText            = Observed mean value
mean.field.toolTipText      = ${mean.toolTipText}

stdDev.text                 = Observed std dev
stdDev.toolTipText          = Observed standard deviation value
stdDev.field.toolTipText    = ${stdDev.toolTipText}

threshold.text              = Threshold
threshold.toolTipText       = Threshold, either global or locally computed
threshold.field.toolTipText = ${threshold.toolTipText}


