# ---------------------------------------------------------------------------- #
#                                                                              #
#            B i n a r i z a t i o n B o a r d . p r o p e r t i e s           #
#                                                                              #
# ---------------------------------------------------------------------------- #

# This file gathers resources to be injected in the BinarizationBoard class
#
# This is the generic version

adaptiveFilter.text         = Use adaptive filter (recommended)
adaptiveFilter.toolTipText  = Converts a pixel to black and white by looking at its surrounding pixels

adaptiveMean.text           = Mean coef
adaptiveMean.toolTipText    = Coefficient for mean value
adaptiveMean.field.toolTipText = ${adaptiveMean.toolTipText}

adaptiveStdDev.text         = Std Dev coef
adaptiveStdDev.toolTipText  = Coefficient for standard deviation value
adaptiveStdDev.field.toolTipText = ${adaptiveStdDev.toolTipText}

apply.text                  = Apply (enter)
apply.toolTipText           = Apply the filter & settings on the sheet gray image
apply.field.toolTipText     = ${apply.toolTipText}

applyToWholeBook.text       = Apply to whole book
applyToWholeBook.toolTipText    = Define this filter & settings for the whole book
applyToWholeBook.field.toolTipText = ${applyToWholeBook.toolTipText}

globalFilter.text           = Use global filter
globalFilter.toolTipText    = Converts to black and white by using one threshold value for the entire image

globalThreshold.text        = Threshold
globalThreshold.toolTipText = Gray threshold
globalThreshold.field.toolTipText = ${globalThreshold.toolTipText}

noGraySourceLabel.text          = No gray image available for binarization
noGraySourceLabel.toolTipText   = There is no source image available to run binarization on

overwrite.text              = Overwrite sheets?
overwrite.toolTipText       = When applying to the whole book, overwrite individual sheets' binarization settings
overwrite.field.toolTipText = ${overwrite.toolTipText}

reset.text                  = Reset
reset.toolTipText           = Reset to the default filter & settings for this sheet
reset.field.toolTipText     = ${reset.toolTipText}
