# ------------------------------------------------------------------------------------------------ #
#                                                                                                  #
#                                 S c a l e . p r o p e r t i e s                                  #
#                                                                                                  #
# ------------------------------------------------------------------------------------------------ #

# This file gathers resources to be injected in the Scale class
#
# This is the generic version

# Descriptions for class Scale.Item
Item.line.text              = Line thickness
Item.interline.text         = Interline
Item.smallInterline.text    = Small interline
Item.beam.text              = Beam thickness
Item.smallBeam.text         = Small beam thickness
Item.stem.text              = Stem thickness
