# ------------------------------------------------------------------------------------------------ #
#                                                                                                  #
#                             S c a l e I t e m . p r o p e r t i e s                              #
#                                                                                                  #
# ------------------------------------------------------------------------------------------------ #

# This file gathers resources to be injected in the ScaleItem class
#
# This is the generic version

line.text                  = Line thickness
line.toolTipText           = Most frequent value for vertical line thickness

interline.text             = Interline
interline.toolTipText      = Vertical distance between lines, center to center

smallInterline.text        = Small interline
smallInterline.toolTipText = Only if there is a population of small staves

beam.text                  = Beam thickness
beam.toolTipText           = Prefer slightly smaller to slightly larger

smallBeam.text             = Small beam thickness
smallBeam.toolTipText      = Only if there is a population of small beams

stem.text                  = Stem thickness
stem.toolTipText           = Value determined during the STEM_SEEDS step
