# ------------------------------------------------------------------------------------------------ #
#                                                                                                  #
#                               V e r s i o n s . p r o p e r t i e s                              #
#                                                                                                  #
# ------------------------------------------------------------------------------------------------ #

# This file gathers resources to be injected in the Versions class.
#
# This is the generic (english) version

# AbstractPanel

status.text = Status:
status.toolTipText = Software status
status.field.toolTipText = ${status.toolTipText}

tag.text = Release:
tag.toolTipText = Latest release
tag.field.toolTipText = ${tag.toolTipText}

polling.text = Polling:
polling.toolTipText = Frequency for release check
polling.field.toolTipText = ${polling.toolTipText}

# NegativePanel

Negative.title = Software is up-to-date
Negative.msg = No newer release is available yet

# PositivePanel

Positive.title = New Audiveris release available
Positive.msg = A new Audiveris release is available!

published.text = Published on:
published.toolTipText = Publication date
published.field.toolTipText = ${published.toolTipText}

url.text = URL:
url.toolTipText = Hyperlink to release web page
url.field.toolTipText = ${url.toolTipText}

releaseTitle.text = Title:
releaseTitle.toolTipText = Release title
releaseTitle.field.toolTipText = ${releaseTitle.toolTipText}

content.text = Content:
content.toolTipText = Release content
content.field.toolTipText = ${content.toolTipText}

