# ------------------------------------------------------------------------------------------------ #
#                                                                                                  #
#                                 S h a p e . p r o p e r t i e s                                  #
#                                                                                                  #
# ------------------------------------------------------------------------------------------------ #

# This file gathers resources to be injected in the Shape class
#
# This is the generic version

#
# Sets ---
#

DOT_set.text = Dot set
DOT_set.toolTipText = -- not yet provided

HW_REST_set.text = Half & Whole Rest set
HW_REST_set.toolTipText = -- not yet provided

EIGHTH_set.text = Grace & beat unit set
EIGHTH_set.toolTipText = -- not yet provided

#
# Bars ---
#
DAL_SEGNO.text = D.S.: Repeat from the sign
DAL_SEGNO.toolTipText = -- not yet provided

DA_CAPO.text = D.C.: Repeat from the beginning

SEGNO.text = Sign

CODA.text = Closing section

BREATH_MARK.text = Breath Mark

CAESURA.text = Caesura

FERMATA.text = Fermata arc + dot

FERMATA_BELOW.text = Fermata below, arc + dot

REPEAT_ONE_BAR.text = Repeat last bar

REPEAT_TWO_BARS.text = Repeat last two bars

REPEAT_FOUR_BARS.text = Repeat last four bars

#
# Clefs ---
#
G_CLEF.text = Treble Clef
G_CLEF_SMALL.text = Small Treble Clef
G_CLEF_8VA.text = Treble Clef Ottava Alta
G_CLEF_8VB.text = Treble Clef Ottava Bassa
C_CLEF.text = Ut Clef
F_CLEF.text = Bass Clef
F_CLEF_SMALL.text = Small Bass Clef
F_CLEF_8VA.text = Bass Clef Ottava Alta
F_CLEF_8VB.text = Bass Clef Ottava Bassa
PERCUSSION_CLEF.text = Percussion Clef
###CLEF_OTTAVA.text = Clef 8 Not handled without its related clef

#
# Accidentals ---
#
FLAT.text = Minus one half step
NATURAL.text = Natural value
SHARP.text = Plus one half step
DOUBLE_SHARP.text = Double Sharp
DOUBLE_FLAT.text = Double Flat

#
# Time ---
#
TIME_ZERO.text = Time digit 0
TIME_ONE.text = Time digit 1
TIME_TWO.text = Time digit 2
TIME_THREE.text = Time digit 3
TIME_FOUR.text = Time digit 4
TIME_FIVE.text = Time digit 5
TIME_SIX.text = Time digit 6
TIME_SEVEN.text = Time digit 7
TIME_EIGHT.text = Time digit 8
TIME_NINE.text = Time digit 9
TIME_TWELVE.text = Time number 12
TIME_SIXTEEN.text = Time number 16

# Whole time sigs
COMMON_TIME.text = Alpha = 4/4
CUT_TIME.text = Semi-Alpha = 2/2

# Predefined time combos
TIME_FOUR_FOUR.text = Rational 4/4
TIME_TWO_TWO.text = Rational 2/2
TIME_TWO_FOUR.text = Rational 2/4
TIME_THREE_FOUR.text = Rational 3/4
TIME_FIVE_FOUR.text = Rational 5/4
TIME_SIX_FOUR.text = Rational 6/4
TIME_THREE_EIGHT.text = Rational 3/8
TIME_SIX_EIGHT.text = Rational 6/8
TIME_TWELVE_EIGHT.text = Rational 12/8

#
# Octave shifts ---
#
OTTAVA.text = 8
QUINDICESIMA.text = 15
VENTIDUESIMA.text = 22

#
# Rests ---
#
LONG_REST.text = Rest for 4 measures
BREVE_REST.text = Rest for 2 measures
QUARTER_REST.text = Rest for a 1/4
EIGHTH_REST.text = Rest for a 1/8
ONE_16TH_REST.text = Rest for a 1/16
ONE_32ND_REST.text = Rest for a 1/32
ONE_64TH_REST.text = Rest for a 1/64
ONE_128TH_REST.text = Rest for a 1/128

#
# Flags ---
#
FLAG_1.text = Single flag
FLAG_1_DOWN.text = Single flag down
FLAG_2.text = Double flag
FLAG_2_DOWN.text = Double flag down
FLAG_3.text = Triple flag
FLAG_3_DOWN.text = Triple flag down
FLAG_4.text = Quadruple flag
FLAG_4_DOWN.text = Quadruple flag down
FLAG_5.text = Quintuple flag
FLAG_5_DOWN.text = Quintuple flag down

#
# Small Flags
#
SMALL_FLAG.text = Flag for grace note
SMALL_FLAG_DOWN.text = Flag for grace note down
SMALL_FLAG_SLASH.text = Slashed flag for grace note
SMALL_FLAG_SLASH_DOWN.text = Slashed flag for grace note down

#
# Grace notes ---
#
###GRACE_NOTE.text = Grace Note with no slash # Handled by EIGHTH_set
GRACE_NOTE_DOWN.text = Grace Note down with no slash
GRACE_NOTE_SLASH.text = Grace Note with a slash
GRACE_NOTE_SLASH_DOWN.text = Grace Note down with a slash

#
# Notes for metronome indication ---
#
METRO_WHOLE.text = Metronome whole note
METRO_HALF.text = Metronome half note
METRO_QUARTER.text = Metronome quarter note
###METRO_EIGHTH.text = Metronome 8th note  # Handled by EIGHTH_set
METRO_SIXTEENTH.text = Metronome 16th note
METRO_DOTTED_HALF.text = Metronome dotted half note
METRO_DOTTED_QUARTER.text = Metronome dotted quarter note
METRO_DOTTED_EIGHTH.text = Metronome dotted 8th note
METRO_DOTTED_SIXTEENTH.text = Metronome dotted 16th note

#
# Articulations ---
#
ACCENT,
TENUTO,
STACCATISSIMO,
STACCATISSIMO_BELOW,
MARCATO,
MARCATO_BELOW,
ARPEGGIATO,

#
# Dynamics ---
#
#    DYNAMICS_CHAR_M.text = m character
#    DYNAMICS_CHAR_R.text = r character
#    DYNAMICS_CHAR_S.text = s character
#    DYNAMICS_CHAR_Z.text = z character
#    DYNAMICS_FZ.text = Forzando
#    DYNAMICS_RF,
#    DYNAMICS_RFZ.text = Rinforzando
#    DYNAMICS_SFFZ,
#    DYNAMICS_SFP.text = Subito fortepiano
#    DYNAMICS_SFPP,
DYNAMICS_P.text = Piano
DYNAMICS_PP.text = Pianissimo
DYNAMICS_PPP.text = Pianississimo
DYNAMICS_MP.text = Mezzo piano
DYNAMICS_F.text = Forte
DYNAMICS_FF.text = Fortissimo
DYNAMICS_FFF.text = Fortississimo
DYNAMICS_MF.text = Mezzo forte
DYNAMICS_FP.text = FortePiano
DYNAMICS_FZ.text = Forzando
DYNAMICS_SF.text = Subito forte
DYNAMICS_SFZ.text = Sforzando

#
# Ornaments ---
#
TR.text = Trill
TURN.text = Turn
TURN_INVERTED.text = Inverted Turn
TURN_UP.text = Turn Up
TURN_SLASH.text = Turn with a Slash
MORDENT.text = Lower mordent (with bisecting vertical line)
MORDENT_INVERTED.text = Upper mordent (no vertical line)

#
# Tuplets ---
#
TUPLET_THREE.text = 3
TUPLET_SIX.text = 6

#
# Techniques ---
#
BOW_DOWN.text = stringsDownBow
BOW_UP.text = stringsUpBow
PEDAL_MARK.text = Pedal down
PEDAL_UP_MARK.text = Pedal downup

#
# Small digits ---
#
DIGIT_0.text = Digit 0
DIGIT_1.text = Digit 1
DIGIT_2.text = Digit 2
DIGIT_3.text = Digit 3
DIGIT_4.text = Digit 4
DIGIT_5.text = Digit 5
#    DIGIT_6.text = Digit 6
#    DIGIT_7.text = Digit 7
#    DIGIT_8.text = Digit 8
#    DIGIT_9.text = Digit 9

#
# Roman numerals ---
#
ROMAN_I.text = Roman number 1
ROMAN_II.text = Roman number 2
ROMAN_III.text = Roman number 3
ROMAN_IV.text = Roman number 4
ROMAN_V.text = Roman number 5
ROMAN_VI.text = Roman number 6
ROMAN_VII.text = Roman number 7
ROMAN_VIII.text = Roman number 8
ROMAN_IX.text = Roman number 9
ROMAN_X.text = Roman number 10
ROMAN_XI.text = Roman number 11
ROMAN_XII.text = Roman number 12

#
# Plucking ---
#
PLUCK_P.text = Plucking pouce/pulgar/thumb
PLUCK_I.text = Plucking index/indicio/index
PLUCK_M.text = Plucking majeur/medio/middle
PLUCK_A.text = Plucking annulaire/anular/ring

#
# Percussion playing technique ---
#
PLAYING_OPEN.text = Pict open: o
PLAYING_HALF_OPEN.text = Pict half-open: \u00f8
PLAYING_CLOSED.text = Pict closed: +

#
# Tremolos
#
TREMOLO_1.text = Single tremolo
TREMOLO_2.text = Double tremolo
TREMOLO_3.text = Triple tremolo

#
# Miscellaneous ---
#
CLUTTER.text = Pure clutter

#/**
# * =============================================================================================
# * End of physical shapes
# * Beginning of logical shapes, their order is irrelevant
# * All head shapes are among them, they are recognized by template matching
# * =============================================================================================
# */

TEXT.text = Sequence of letters & spaces
CHARACTER.text = Any letter

#
# Shapes based on physical DOT_set ---
#
REPEAT_DOT.text = Repeat dot
AUGMENTATION_DOT.text = Augmentation Dot
STACCATO.text = Staccato dot"

#
# Shapes based on physical HW_REST_set ---
#
WHOLE_REST.text = Rest for a 1
HALF_REST.text = Rest for a 1/2

#
# Shapes based on physical EIGHTH_set ---
#
GRACE_NOTE.text = Grace Note with no slash
METRO_EIGHTH.text = Metronome 8th note

#
# StemLessHeads duration 2 ---
#
BREVE.text = Double Whole
BREVE_SMALL.text = Small Double Whole
BREVE_CROSS.text = Double Whole Cross
BREVE_DIAMOND.text = Double Whole Diamond
BREVE_TRIANGLE_DOWN.text = Double Whole Triangle Down
BREVE_CIRCLE_X.text = Double Whole Circle X

#
# StemLessHeads duration 1 ---
#
WHOLE_NOTE.text = Hollow node head for wholes
WHOLE_NOTE_SMALL.text = Small hollow node head for grace or cue wholes
WHOLE_NOTE_CROSS.text = Hollow cross shape note head for unpitched percussion wholes
WHOLE_NOTE_DIAMOND.text = Hollow diamond-shaped note head for unpitched percussion wholes
WHOLE_NOTE_TRIANGLE_DOWN.text = Hollow point-down triangle shape for unpitched percussion wholes
WHOLE_NOTE_CIRCLE_X.text = Stemless circle-x head shape for unpitched percussion wholes

#
# Noteheads duration 1/2 ---
#
NOTEHEAD_VOID.text = Hollow note head for halves
NOTEHEAD_VOID_SMALL.text = Small hollow note head for grace or cue
NOTEHEAD_CROSS_VOID.text = Hollow cross shape note head for unpitched percussion
NOTEHEAD_DIAMOND_VOID.text = Hollow diamond shape note head for unpitched percussion
NOTEHEAD_TRIANGLE_DOWN_VOID.text = Hollow point-down triangle shape note head for unpitched percussion
NOTEHEAD_CIRCLE_X_VOID.text = Hollow circle-x shape note head for unpitched percussion

#
# Noteheads duration 1/4 ---
#
NOTEHEAD_BLACK.text = Filled note head for quarters and less
NOTEHEAD_BLACK_SMALL.text = Small filled note head for grace or cue
NOTEHEAD_CROSS.text = Ghost note with rhythmic value but no discernible pitch
NOTEHEAD_DIAMOND_FILLED.text = Filled diamond shape note head for unpitched percussion
NOTEHEAD_TRIANGLE_DOWN_FILLED.text = Filled point-down triangle shape note head for unpitched percussion
NOTEHEAD_CIRCLE_X.text = Circle-x shape note head for unpitched percussion

#
# Compound notes ---
#
SIXTEENTH_NOTE_UP.text = Filled head plus its up stem and two flags
DOTTED_SIXTEENTH_NOTE_UP.text = Filled head plus its up stem, two flag and dot
EIGHTH_NOTE_UP.text = Filled head plus its up stem and flag
DOTTED_EIGHTH_NOTE_UP.text = Filled head plus its up stem, flag and dot
QUARTER_NOTE_UP.text = Filled head plus its up stem
QUARTER_NOTE_DOWN.text = Filled head plus its down stem
DOTTED_QUARTER_NOTE_UP.text = Filled head plus its up stem and dot
HALF_NOTE_UP.text = Hollow head plus its up stem
HALF_NOTE_DOWN.text = Hollow head plus its down stem
DOTTED_HALF_NOTE_UP.text = Hollow head plus its up stem and dot

#
# Beams and slurs ---
#
BEAM.text = Beam between two stems
BEAM_SMALL.text = Small beam for cue notes
BEAM_HOOK.text = Hook of a beam attached on one stem
BEAM_HOOK_SMALL.text = Small hook of a beam for cue notes
SLUR.text = Slur above or below notes
SLUR_ABOVE.text = Slur above notes
SLUR_BELOW.text = Slur below notes
MULTIPLE_REST.text = Multiple measure rest
MULTIPLE_REST_LEFT.text = Multiple measure rest left
MULTIPLE_REST_MIDDLE.text = Multiple measure rest middle
MULTIPLE_REST_RIGHT.text = Multiple measure rest right

#
# Key signatures ---
#
KEY_FLAT_7.text = Seven Flats
KEY_FLAT_6.text = Six Flats
KEY_FLAT_5.text = Five Flats
KEY_FLAT_4.text = Four Flats
KEY_FLAT_3.text = Three Flats
KEY_FLAT_2.text = Two Flats
KEY_FLAT_1.text = One Flat
KEY_CANCEL.text = Key Cancel
KEY_SHARP_1.text = One Sharp
KEY_SHARP_2.text = Two Sharps
KEY_SHARP_3.text = Three Sharps
KEY_SHARP_4.text = Four Sharps
KEY_SHARP_5.text = Five Sharps
KEY_SHARP_6.text = Six Sharps
KEY_SHARP_7.text = Seven Sharps

#
# Bars ---
#
DUMMY_BARLINE.text = Dummy bar line
THIN_BARLINE.text = Thin bar line
THIN_CONNECTOR.text = Connector between thin barlines
THICK_BARLINE.text = Thick bar line
THICK_CONNECTOR.text = Connector between thick barlines
BRACKET_CONNECTOR.text = Connector between bracket items
DOUBLE_BARLINE.text = Double thin bar line
FINAL_BARLINE.text = Thin / Thick bar line
REVERSE_FINAL_BARLINE.text = Thick / Thin bar line
LEFT_REPEAT_SIGN.text = Thick / Thin bar line + Repeat dots
RIGHT_REPEAT_SIGN.text = Repeat dots + Thin / Thick bar line
BACK_TO_BACK_REPEAT_SIGN.text = Repeat dots + Thin / Thick / Thin  + Repeat dots
ENDING.text = Alternate ending
ENDING_WRL.text = Alternate ending with right leg

#
# Wedges ---
#
CRESCENDO.text = Crescendo
DIMINUENDO.text = Diminuendo

#
# Miscellaneous ---
#
BRACE.text = Brace
BRACKET.text = Bracket
REPEAT_DOT_PAIR.text = Pair of repeat dots
NOISE.text = Too small stuff
LEDGER.text = Ledger
SEGMENT.text = Wedge or ending segment
LYRICS.text = Lyrics
METRONOME.text = Text-based notes

#
# Stems ---
#
STEM.text = Stem
VERTICAL_SERIF.text = Vertical serif

#
# Other stuff ---
#
FORWARD.text = To indicate a forward
NON_DRAGGABLE.text = Non draggable shape
GLYPH_PART.text = Part of a larger glyph
NUMBER_CUSTOM.text = Number defined by user
TIME_CUSTOM.text = Time signature defined by user
NO_LEGAL_TIME.text = No Legal Time Shape
BRACKET_UPPER_SERIF.text = Top serif of a bracket
BRACKET_LOWER_SERIF.text = Bottom serif of a bracket
STAFF_LINES.text = 5-line staff

#
# Obsolete, kept for backward compatibility ---
#
FLAG_1_UP.text = OBSOLETE Single flag up
FLAG_2_UP.text = OBSOLETE Double flag up
FLAG_3_UP.text = OBSOLETE Triple flag up
FLAG_4_UP.text = OBSOLETE Quadruple flag up
FLAG_5_UP.text = OBSOLETE Quintuple flag up
FERMATA_DOT.text = Fermata dot
FERMATA_ARC.text = Fermata arc, without dot
FERMATA_ARC_BELOW.text = Fermata arc below, without dot
STRONG_ACCENT.text = Marcato
