# ---------------------------------------------------------------------------- #
#                                                                              #
#                  S a m p l e B o a r d . p r o p e r t i e s                 #
#                                                                              #
# ---------------------------------------------------------------------------- #

# This file gathers resources to be injected in the SampleBoard class
#
# This is the generic version

sheetName.text              = Sheet:
sheetName.toolTipText       = Containing sheet
sheetName.field.toolTipText = ${sheetName.toolTipText}

iLine.text                  = iLine:
iLine.toolTipText           = Interline value in pixels
iLine.field.toolTipText     = ${iLine.toolTipText}

weight.text                 = Weight:
weight.toolTipText          = Normalized weight
weight.field.toolTipText    = ${weight.toolTipText}

width.text                  = Width:
width.toolTipText           = Normalized width
width.field.toolTipText     = ${width.toolTipText}

height.text                 = Height:
height.toolTipText          = Normalized height
height.field.toolTipText    = ${height.toolTipText}

pitch.text                  = Pitch:
pitch.toolTipText           = Staff-based pitch
pitch.field.toolTipText     = ${pitch.toolTipText}

shape.text                  = Shape:
shape.toolTipText           = Shape for this sample
shape.field.toolTipText     = ${shape.toolTipText}
