package org.audiveris.omr.classifier;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.Arrays;

/**
 * Class {@code AnnotationFactory} produces the symbol corresponding to the symbol ID.
 *
 * @author Raphael Emberger
 */
public class AnnotationFactory {

    //~ Static fields/initializers -----------------------------------------------------------------

    private static final Logger logger = LoggerFactory.getLogger(AnnotationFactory.class);

    private static final ArrayList<Annotation> ANNOTATIONS = new ArrayList<>(Arrays.asList(
            new Annotation(0, "none", "No valid symbol"),
            new Annotation(1, "brace", "Brace"),
            new Annotation(2, "bracketTop", "Bracket top"),
            new Annotation(3, "bracketBottom", "Bracket bottom"),
            new Annotation(4, "legerLine", "Leger line"),
            new Annotation(5, "barlineSingle", "Single barline"),
            new Annotation(6, "barlineDouble", "Double barline"),
            new Annotation(7, "barlineFinal", "Final barline"),
            new Annotation(8, "barlineReverseFinal", "Reverse final barline"),
            new Annotation(9, "barlineHeavy", "Heavy barline"),
            new Annotation(10, "barlineHeavyHeavy", "Heavy double barline"),
            new Annotation(11, "barlineDashed", "Dashed barline"),
            new Annotation(12, "barlineDotted", "Dotted barline"),
            new Annotation(13, "repeatLeft", "Left (start) repeat sign"),
            new Annotation(14, "repeatRight", "Right (end) repeat sign"),
            new Annotation(15, "repeatRightLeft", "Right and left repeat sign"),
            new Annotation(16, "repeatDots", "Repeat dots"),
            new Annotation(17, "repeatDot", "Repeat dot"),
            new Annotation(18, "dalSegno", "Dal segno (D.S.)"),
            new Annotation(19, "daCapo", "Da capo (D.C.)"),
            new Annotation(20, "segno", "Segno"),
            new Annotation(21, "coda", "Coda"),
            new Annotation(22, "codaSquare", "Square coda"),
            new Annotation(23, "gClef", "G clef"),
            new Annotation(24, "gClef8vb", "G clef ottava bassa"),
            new Annotation(25, "gClef8va", "G clef ottava alta"),
            new Annotation(26, "gClef15mb", "G clef quindicesima bassa"),
            new Annotation(27, "gClef15ma", "G clef quindicesima alta"),
            new Annotation(28, "cClefAlto", "C clef alto"),
            new Annotation(29, "cClefTenor", "C clef tenor"),
            new Annotation(30, "fClef", "F clef"),
            new Annotation(31, "fClef8vb", "F clef ottava bassa"),
            new Annotation(32, "fClef8va", "F clef ottava alta"),
            new Annotation(33, "fClef15mb", "F clef quindicesima bassa"),
            new Annotation(34, "fClef15ma", "F clef quindicesima alta"),
            new Annotation(35, "unpitchedPercussionClef1", "Unpitched percussion clef 1"),
            new Annotation(36, "gClefChange", "G clef change"),
            new Annotation(37, "cClefAltoChange", "C clef alto change"),
            new Annotation(38, "cClefTenorChange", "C clef tenor change"),
            new Annotation(39, "fClefChange", "F clef change"),
            new Annotation(40, "clef8", "8 for clefs"),
            new Annotation(41, "clef15", "15 for clefs"),
            new Annotation(42, "timeSig0", "Time signature 0"),
            new Annotation(43, "timeSig1", "Time signature 1"),
            new Annotation(44, "timeSig2", "Time signature 2"),
            new Annotation(45, "timeSig3", "Time signature 3"),
            new Annotation(46, "timeSig4", "Time signature 4"),
            new Annotation(47, "timeSig5", "Time signature 5"),
            new Annotation(48, "timeSig6", "Time signature 6"),
            new Annotation(49, "timeSig7", "Time signature 7"),
            new Annotation(50, "timeSig8", "Time signature 8"),
            new Annotation(51, "timeSig9", "Time signature 9"),
            new Annotation(52, "timeSig12", "Time signature 12"),
            new Annotation(53, "timeSig16", "Time signature 16"),
            new Annotation(54, "timeSigCommon", "Common time"),
            new Annotation(55, "timeSigCutCommon", "Cut time"),
            new Annotation(56, "timeSig2over4", "2/4 time signature"),
            new Annotation(57, "timeSig2over2", "2/2 time signature"),
            new Annotation(58, "timeSig3over2", "3/2 time signature"),
            new Annotation(59, "timeSig3over4", "3/4 time signature"),
            new Annotation(60, "timeSig3over8", "3/8 time signature"),
            new Annotation(61, "timeSig4over4", "4/4 time signature"),
            new Annotation(62, "timeSig5over4", "5/4 time signature"),
            new Annotation(63, "timeSig5over8", "5/8 time signature"),
            new Annotation(64, "timeSig6over4", "6/4 time signature"),
            new Annotation(65, "timeSig6over8", "6/8 time signature"),
            new Annotation(66, "timeSig7over8", "7/8 time signature"),
            new Annotation(67, "timeSig9over8", "9/8 time signature"),
            new Annotation(68, "timeSig12over8", "12/8 time signature"),
            new Annotation(69, "noteheadBlack", "Black notehead"),
            new Annotation(70, "noteheadBlackSmall", "Black notehead (small staff)"),
            new Annotation(71, "noteheadHalf", "Half (minim) notehead"),
            new Annotation(72, "noteheadHalfSmall", "Half (minim) notehead (small staff)"),
            new Annotation(73, "noteheadWhole", "Whole (semibreve) notehead"),
            new Annotation(74, "noteheadWholeSmall", "Whole notehead (small staff)"),
            new Annotation(75, "noteheadDoubleWhole", "Double whole (breve) notehead"),
            new Annotation(76, "noteheadDoubleWholeSmall", "Double whole note (breve) (small staff)"),
            new Annotation(77, "noteheadXBlack", "X notehead black"),
            new Annotation(78, "noteheadXHalf", "X notehead half"),
            new Annotation(79, "noteheadXWhole", "X notehead whole"),
            new Annotation(80, "augmentationDot", "Augmentation dot"),
            new Annotation(81, "stem", "Combining stem"),
            new Annotation(82, "tremolo1", "Combining tremolo 1"),
            new Annotation(83, "tremolo2", "Combining tremolo 2"),
            new Annotation(84, "tremolo3", "Combining tremolo 3"),
            new Annotation(85, "tremolo4", "Combining tremolo 4"),
            new Annotation(86, "tremolo5", "Combining tremolo 5"),
            new Annotation(87, "flag8thUp", "Combining flag 1 (8th) above"),
            new Annotation(88, "flag8thUpSmall", "Combining flag 1 (8th) above (small staff)"),
            new Annotation(89, "flag16thUp", "Combining flag 2 (16th) above"),
            new Annotation(90, "flag32ndUp", "Combining flag 3 (32nd) above"),
            new Annotation(91, "flag64thUp", "Combining flag 4 (64th) above"),
            new Annotation(92, "flag128thUp", "Combining flag 5 (128th) above"),
            new Annotation(93, "flag256thUp", "Combining flag 6 (256th) above"),
            new Annotation(94, "flag512thUp", "Combining flag 7 (512th) above"),
            new Annotation(95, "flag1024thUp", "Combining flag 8 (1024th) above"),
            new Annotation(96, "flag8thDown", "Combining flag 1 (8th) below"),
            new Annotation(97, "flag8thDownSmall", "Combining flag 1 (8th) below (small staff)"),
            new Annotation(98, "flag16thDown", "Combining flag 2 (16th) below"),
            new Annotation(99, "flag32ndDown", "Combining flag 3 (32nd) below"),
            new Annotation(100, "flag64thDown", "Combining flag 4 (64th) below"),
            new Annotation(101, "flag128thDown", "Combining flag 5 (128th) below"),
            new Annotation(102, "flag256thDown", "Combining flag 6 (256th) below"),
            new Annotation(103, "flag512thDown", "Combining flag 7 (512th) below"),
            new Annotation(104, "flag1024thDown", "Combining flag 8 (1024th) below"),
            new Annotation(105, "accidentalFlat", "Flat"),
            new Annotation(106, "accidentalFlatSmall", "Flat (for small staves)"),
            new Annotation(107, "accidentalNatural", "Natural"),
            new Annotation(108, "accidentalNaturalSmall", "Natural (for small staves)"),
            new Annotation(109, "accidentalSharp", "Sharp"),
            new Annotation(110, "accidentalSharpSmall", "Sharp (for small staves)"),
            new Annotation(111, "accidentalDoubleSharp", "Double sharp"),
            new Annotation(112, "accidentalDoubleFlat", "Double flat"),
            new Annotation(113, "keyFlat", "Flat in key signature"),
            new Annotation(114, "keyNatural", "Natural in key signature"),
            new Annotation(115, "keySharp", "Sharp in key signature"),
            new Annotation(116, "articAccentAbove", "Accent above"),
            new Annotation(117, "articAccentBelow", "Accent below"),
            new Annotation(118, "articStaccatoAbove", "Staccato above"),
            new Annotation(119, "articStaccatoBelow", "Staccato below"),
            new Annotation(120, "articTenutoAbove", "Tenuto above"),
            new Annotation(121, "articTenutoBelow", "Tenuto below"),
            new Annotation(122, "articStaccatissimoAbove", "Staccatissimo above"),
            new Annotation(123, "articStaccatissimoBelow", "Staccatissimo below"),
            new Annotation(124, "articMarcatoAbove", "Marcato above"),
            new Annotation(125, "articMarcatoBelow", "Marcato below"),
            new Annotation(126, "articTenutoStaccatoAbove", "Louré (tenuto-staccato) above"),
            new Annotation(127, "articTenutoStaccatoBelow", "Louré (tenuto-staccato) below"),
            new Annotation(128, "fermataAbove", "Fermata above staff"),
            new Annotation(129, "fermataBelow", "Fermata below staff"),
            new Annotation(130, "breathMarkComma", "Breath mark (comma)"),
            new Annotation(131, "caesura", "Caesura"),
            new Annotation(132, "restMaxima", "Maxima rest"),
            new Annotation(133, "restLonga", "Longa rest"),
            new Annotation(134, "restDoubleWhole", "Double whole (breve) rest"),
            new Annotation(135, "restWhole", "Whole (semibreve) rest"),
            new Annotation(136, "restHalf", "Half (minim) rest"),
            new Annotation(137, "restQuarter", "Quarter (crotchet) rest"),
            new Annotation(138, "rest8th", "Eighth (quaver) rest"),
            new Annotation(139, "rest16th", "16th (semiquaver) rest"),
            new Annotation(140, "rest32nd", "32nd (demisemiquaver) rest"),
            new Annotation(141, "rest64th", "64th (hemidemisemiquaver) rest"),
            new Annotation(142, "rest128th", "128th (semihemidemisemiquaver) rest"),
            new Annotation(143, "rest256th", "256th rest"),
            new Annotation(144, "rest512th", "512th rest"),
            new Annotation(145, "rest1024th", "1024th rest"),
            new Annotation(146, "restHBar", "Multiple measure rest"),
            new Annotation(147, "ottavaAlta", "Ottava alta (8va)"),
            new Annotation(148, "ottavaBassaVb", "Ottava bassa (8vb)"),
            new Annotation(149, "dynamicPiano", "Piano (p)"),
            new Annotation(150, "dynamicMezzo", "Mezzo (m)"),
            new Annotation(151, "dynamicForte", "Forte (f)"),
            new Annotation(152, "dynamicRinforzando", "Rinforzando (r)"),
            new Annotation(153, "dynamicSforzando", "Sforzando (s)"),
            new Annotation(154, "dynamicZ", "Z"),
            new Annotation(155, "dynamicNiente", "Niente (n)"),
            new Annotation(156, "dynamicPPPPPP", "pppppp"),
            new Annotation(157, "dynamicPPPPP", "ppppp"),
            new Annotation(158, "dynamicPPPP", "pppp"),
            new Annotation(159, "dynamicPPP", "ppp"),
            new Annotation(160, "dynamicPP", "pp"),
            new Annotation(161, "dynamicMP", "mp"),
            new Annotation(162, "dynamicMF", "mf"),
            new Annotation(163, "dynamicPF", "pf"),
            new Annotation(164, "dynamicFF", "ff"),
            new Annotation(165, "dynamicFFF", "fff"),
            new Annotation(166, "dynamicFFFF", "ffff"),
            new Annotation(167, "dynamicFFFFF", "fffff"),
            new Annotation(168, "dynamicFFFFFF", "ffffff"),
            new Annotation(169, "dynamicFortePiano", "Forte-piano (fp)"),
            new Annotation(170, "dynamicForzando", "Forzando (fz)"),
            new Annotation(171, "dynamicSforzando1", "Sforzando 1 (sf)"),
            new Annotation(172, "dynamicSforzandoPiano", "Sforzando-piano (sfp)"),
            new Annotation(173, "dynamicSforzandoPianissimo", "Sforzando-pianissimo (sfpp)"),
            new Annotation(174, "dynamicSforzato", "Sforzato (sfz)"),
            new Annotation(175, "dynamicSforzatoPiano", "Sforzato-piano (sfzp)"),
            new Annotation(176, "dynamicSforzatoFF", "Sforzatissimo (sffz)"),
            new Annotation(177, "dynamicRinforzando1", "Rinforzando 1 (rf)"),
            new Annotation(178, "dynamicRinforzando2", "Rinforzando 2 (rfz)"),
            new Annotation(179, "graceNoteAcciaccaturaStemUp", "Slashed grace note stem up"),
            new Annotation(180, "graceNoteAppoggiaturaStemUp", "Grace note stem up"),
            new Annotation(181, "graceNoteAcciaccaturaStemDown", "Slashed grace note stem down"),
            new Annotation(182, "graceNoteAppoggiaturaStemDown", "Grace note stem down"),
            new Annotation(181, "ornamentTrill", "Trill"),
            new Annotation(182, "ornamentTurn", "Turn"),
            new Annotation(183, "ornamentTurnInverted", "Inverted turn"),
            new Annotation(184, "ornamentTurnSlash", "Turn with slash"),
            new Annotation(185, "ornamentTurnUp", "Turn up"),
            new Annotation(186, "ornamentMordent", "Mordent"),
            new Annotation(187, "ornamentMordentInverted", "Inverted mordent"),
            new Annotation(188, "stringsDownBow", "Down bow"),
            new Annotation(189, "stringsUpBow", "Up bow"),
            new Annotation(190, "arpeggiato", "Arpeggiato"),
            new Annotation(191, "keyboardPedalPed", "Pedal mark"),
            new Annotation(192, "keyboardPedalUp", "Pedal up mark"),
            new Annotation(193, "tuplet3", "Tuplet 3"),
            new Annotation(194, "tuplet6", "Tuplet 6"),
            new Annotation(195, "fingering0", "Fingering 0 (open string)"),
            new Annotation(196, "fingering1", "Fingering 1 (thumb)"),
            new Annotation(197, "fingering2", "Fingering 2 (index finger)"),
            new Annotation(198, "fingering3", "Fingering 3 (middle finger)"),
            new Annotation(199, "fingering4", "Fingering 4 (ring finger)"),
            new Annotation(200, "fingering5", "Fingering 5 (little finger)"),
            new Annotation(201, "fingeringPLower", "Fingering p (pulgar; right-hand thumb"),
            new Annotation(202, "fingeringILower", "Fingering i (indicio; right-hand index finger for guitar)"),
            new Annotation(203, "fingeringMLower", "Fingering m (medio; right-hand middle finger for guitar)"),
            new Annotation(204, "fingeringALower", "Fingering a (anular; right-hand ring finger for guitar)")));

    //~ Methods ------------------------------------------------------------------------------------
    //---------//
    // produce //
    //---------//

    /**
     * Produces the symbol preset to the corresponding symbol ID.
     *
     * @param symbolId Identifier for the symbol.
     * @return The symbol if found, otherwise null;
     */
    public static Annotation produce(final String symbolId) {
        Annotation sym = null;
        for (Annotation annotation : ANNOTATIONS) {
            if (annotation.getSymbolId().equals(symbolId)) {
                sym = annotation.deepCopy();
            }
        }
        if (sym == null) {
            logger.error("No symbol found for ID \"" + symbolId + "\"");
        }
        return sym;
    }
}
