# ---------------------------------------------------------------------------- #
#                                                                              #
#                   S h a p e B o a r d . p r o p e r t i e s                  #
#                                                                              #
# ---------------------------------------------------------------------------- #

# This file gathers resources to be injected in the ShapeBoard class
#
# This is the generic version

# Trash

trashCan.toolTipText = Trash can for custom shapes
trashCan.icon = ${smallIcons}/filesystems/trashcan_empty.png

trashMenu.text = Trash can

trashClear.text = Clear
trashClear.toolTipText = Empty the whole custom set

history.title = History
globalSets.title = Global Sets
customSet.title = Custom Set
