# ---------------------------------------------------------------------------- #
#                                                                              #
#                   S h a p e B o a r d . p r o p e r t i e s                  #
#                                                                              #
# ---------------------------------------------------------------------------- #

# This file gathers resources to be injected in the ShapeBoard class
#
# This is the generic version

# Trash

trash.shortDescription = Trash can for buttons
trash.smallIcon = ${smallIcons}/filesystems/trashcan_empty.png
trash.largeIcon = ${largeIcons}/filesystems/trashcan_empty.png
