# ---------------------------------------------------------------------------- #
#                                                                              #
#                        B o a r d . p r o p e r t i e s                       #
#                                                                              #
# ---------------------------------------------------------------------------- #

# This file gathers resources to be injected in the Board class
#
# This is the generic version

PIXEL           = Pixel
BINARIZATION    = Binarization filter
BINARY          = Binary pixel
RUN_HORI        = Horizontal run
RUN_VERT        = Vertical run
SECTION_HORI    = Horizontal section
SECTION_VERT    = Vertical section
FILAMENT        = Filament
SAMPLE          = Sample
GLYPH           = Glyph
INTER           = Inter
TEMPLATE        = Template
SHAPE           = Shape
EVAL            = Eval
CHECK           = Check

vip.text        = Vip
vip.toolTipText = Is this entity flagged as VIP?

dump.text           = Dump
dump.toolTipText    = Dump this entity
