# ---------------------------------------------------------------------------- #
#                                                                              #
#                     R u n B o a r d . p r o p e r t i e s                    #
#                                                                              #
# ---------------------------------------------------------------------------- #

# This file gathers resources to be injected in the RunBoard class
#
# This is the generic version

rLength.text                = Length
rLength.toolTipText         = Length of run in pixels
rLength.field.toolTipText   = ${rLength.toolTipText}

rStart.text                = Start
rStart.toolTipText         = Pixel coordinate at start of run
rStart.field.toolTipText   = ${rStart.toolTipText}
