# ---------------------------------------------------------------------------- #
#                                                                              #
#                  P r e f e r e n c e s . p r o p e r t i e s                 #
#                                                                              #
# ---------------------------------------------------------------------------- #

# This file gathers resources to be injected in the Preferences class
#
# This is the generic version


# Resources for Preferences
# -------------------------

Preferences.title   = Preferences

Preferences.ok                  = OK
Preferences.ok.toolTipText      = Commit all modifications and close dialog

Preferences.cancel              = Cancel
Preferences.cancel.toolTipText  = Discard any modification and close dialog

Preferences.reset               = Reset
Preferences.reset.toolTipText   = Reset all items to their factory values

# Topic
# -----

Topic.SWAPPED_SHEETS.text           = Swapped sheets
Topic.SWAPPED_SHEETS.toolTipText    = Automatic swap out of sheets once they are processed

Topic.PARALLEL_SYSTEMS.text         = Parallel systems
Topic.PARALLEL_SYSTEMS.toolTipText  = Systems are processed in parallel for relevant steps

Topic.MULTIPLE_DELETE.text          = Multiple delete
Topic.MULTIPLE_DELETE.toolTipText   = Multiple delete without user confirmation

Topic.CUSTOM_SHAPE_SET.text         = Custom shape set
Topic.CUSTOM_SHAPE_SET.toolTipText  = Handling of a personal set of shapes

Topic.SAMPLES.text                  = Samples
Topic.SAMPLES.toolTipText           = Handling of samples repositories and classifier training

Topic.ANNOTATIONS.text              = Annotation
Topic.ANNOTATIONS.toolTipText       = Production of image annotation with symbols

Topic.PLOTS.text                    = Plots
Topic.PLOTS.toolTipText             = Display of scale / stem / staves plots

Topic.SPECIFIC_VIEWS.text           = Specific views
Topic.SPECIFIC_VIEWS.toolTipText    = Display of specific sheet views

Topic.SPECIFIC_ITEMS.text           = Specific Items
Topic.SPECIFIC_ITEMS.toolTipText    = Specific items shown in sheet view

Topic.DEBUG.text                    = Debug
Topic.DEBUG.toolTipText             = Support for debug features

Topic.WINDOW_LAYOUT.text            = Window layout
Topic.WINDOW_LAYOUT.toolTipText     = Mise en page de la fen\u00eatre principale de l'application

# StandardTopicsPane
#-------------------

StandardTopicsPane.titledBorder.text = Standard topics

# EarlyPane
#----------

EarlyPane.stepBox.toolTipText = Step triggered on image input
EarlyPane.titledBorder.text = Early steps

# PluginPane
#-----------

PluginPane.pluginBox.toolTipText = Plugin launched on MusicXML output
PluginPane.titledBorder.text = Default plugin

# OutputsPane
#------------

OutputsPane.titledBorder.text = Output folder

BrowsePane.text = Browse
BrowsePane.toolTipText = Default output folder.
BrowsePane.title = Selection of default output folder

SiblingPane.text = Input sibling
SiblingPane.desc = Use same folder as input
SiblingPane.toolTipText = This switch can be superseded by CLI "-output" option

SeparatePane.text = Separate folders
SeparatePane.desc = Use a separate folder for each input
SeparatePane.toolTipText = This switch is irrelevant when "Input sibling" is set

# AdvancedTopicsPane
#-------------------

AdvancedTopicsPane.titledBorder.text = Advanced topics (effective at next restart)

# ScalingPane
#------------

ScalingPane.slider.text = Font size

# LocalePane
#------------

LocalePane.localeBox.toolTipText = Locale chosen for application

# ThemePane
#----------

ThemePane.themeBox.toolTipText = Application theme
