name: Build Audiveris installers

on:
  - workflow_dispatch

permissions:
  contents: read

jobs:
  build-linux-installer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Retrieve Gradle properties
        uses: BrycensRanch/read-properties-action@v1
        id: all
        with:
          file: gradle.properties
          all: true

      - name: Setup Java ${{ steps.all.outputs.theMinJavaVersion }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ steps.all.outputs.theMinJavaVersion }}
          distribution: zulu

      - name: Build installer
        uses: gradle/gradle-build-action@v2.7.0
        with:
          arguments: jpackage