
name: Build schema doc

on:
  - workflow_dispatch

permissions:
  contents: write

jobs:
  # Build the schema documentation
  build-schema-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Retrieve Gradle properties
        uses: BrycensRanch/read-properties-action@v1
        id: all
        with:
          file: gradle.properties
          all: true

      - name: Setup Java ${{ steps.all.outputs.theMinJavaVersion }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ steps.all.outputs.theMinJavaVersion }}
          distribution: zulu

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        
      - name: Install xsltproc
        run: |
          sudo apt update
          sudo apt install xsltproc
          xsltproc --version

      - name: Build schema doc
        run: ./gradlew --info :schemas:genSchemaDoc

      - name: Upload schema doc
        id: upload-schema-doc
        uses: actions/upload-artifact@v4
        with:
          name: schema-doc
          path: schemas/build/distributions/*
          compression-level: 0
          overwrite: true
