name: Build Audiveris installers

on:
  - workflow_dispatch

permissions:
  contents: write

jobs:
  build-installer:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Retrieve Gradle properties
        uses: BrycensRanch/read-properties-action@v1
        id: all
        with:
          file: gradle.properties
          all: true

      - name: Setup Java ${{ steps.all.outputs.theMinJavaVersion }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ steps.all.outputs.theMinJavaVersion }}
          distribution: zulu

      - name: Build installer on ${{ matrix.os }}
        uses: gradle/gradle-build-action@v2.7.0
        with:
          arguments: --info jpackage

#      - name: Create release assets
#        run: |
#          tar -czvf my-binary-${{ matrix.os }}.tar.gz packaging/build/dist
#          echo "Binary for ${{ matrix.os }} built and packaged."

      - name: Upload installer
        id: upload-installer
        uses: actions/upload-artifact@v4
        with:
          name: installer-${{ matrix.os }}
          path: packaging/build/dist/*
          compression-level: 0
          overwrite: true

      - name: Output artifact ID
        run: |
          echo 'Artifact ID is ${{ steps.upload-installer.outputs.artifact-id }}'
          echo 'Artifact URL is ${{ steps.upload-installer.outputs.artifact-url }}'
          echo 'Artifact DIGEST is ${{ steps.upload-installer.outputs.artifact-digest }}'

  global-upload:
    needs: build-installer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download release assets
        uses: actions/download-artifact@v4
        with:
          name: installer-ubuntu-latest
          path: ./binaries

      - name: Download release assets
        uses: actions/download-artifact@v4
        with:
          name: installer-windows-latest
          path: ./binaries

      - name: Download release assets
        uses: actions/download-artifact@v4
        with:
          name: installer-macos-latest
          path: ./binaries

      - name: Create final release assets
        run: tar -czvf all-binaries.tar.gz ./binaries

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true

      - name: Upload final release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step
          asset_path: ./all-binaries.tar.gz
          asset_name: all-binaries.tar.gz
          asset_content_type: application/gzip