name: Test OSes

on:
  - workflow_dispatch

permissions:
  contents: read

jobs:
  # Run the test on each OS
  test-os:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-15, macos-15-large, macos-15-xlarge]

    steps:
      - run: echo hostOS is ${{ matrix.os }}

