# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Windows installer

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2019
    strategy:
      matrix:
        # test against different JDK versions
        java: [ 8 ]
    name: Java ${{ matrix.java }} sample

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: Build with Gradle
      run: ./gradlew installers

    - uses: actions/upload-artifact@v2
      with:
        name: installers
        path: build/installers
